hue:
  host: "192.168.1.163"
  group: "Office"
  username: YuJmLGzA63TaMMKauTFiFKOqzwZ5TFGwwaDJb4bR
  client_key: 2A34F03931105F7F076F9BF0747501DF

nanoleaf:
  host: "192.168.1.32"
  token: "VAE7zu1TMdXcXvbGsV6itpg7vdqYX9TG"
